apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: backend
data:
  application.yml: |
    server:
      port: 8761

    spring:
      application:
        name: discovery-server

    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
      instance:
        hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}